run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    # the following linters are deprecated
    - exhaustivestruct
    - scopelint
    - nosnakecase
    - interfacer
    - maligned
    - ifshort
    - structcheck
    - deadcode
    - golint
    - varcheck