queue_rules:
  - name: default
    conditions:
      - check-success=buildkite/assetbeat
      - check-success=CLA
pull_request_rules:
  - name: self-assign PRs
    conditions:
      - -merged
      - -closed
      - "#assignee=0"
    actions:
      assign:
        add_users:
          - "{{ author }}"
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: |
            This pull request is now in conflicts. Could you fix it @{{author}}? 🙏
            To fixup this pull request, you can check out it locally. See documentation: https://help.github.com/articles/checking-out-pull-requests-locally/
            ```
            git fetch upstream
            git checkout -b {{head}} upstream/{{head}}
            git merge upstream/{{base}}
            git push upstream {{head}}
            ```
  - name: notify the backport policy
    conditions:
      - -label~=^backport
      - base=main
    actions:
      comment:
        message: |
          This pull request does not have a backport label. Could you fix it @{{author}}? 🙏
          To fixup this pull request, you need to add the backport labels for the needed
          branches, such as:
          * `backport-8./d` is the label to automatically backport to the `8./d` branch. `/d` is the digit.

          **NOTE**: `backport-skip` has been added to this pull request.
      label:
        add:
          - backport-skip
  - name: remove backport-skip label
    conditions:
      - label~=^backport-\d
    actions:
      label:
        remove:
          - backport-skip
  - name: notify the backport has not been merged yet
    conditions:
      - -merged
      - -closed
      - author=mergify[bot]
      - "#check-success>0"
      - schedule=Mon-Mon 06:00-10:00[Europe/Paris]
    actions:
      comment:
        message: |
          This pull request has not been merged yet. Could you please review and merge it @{{ assignee | join(', @') }}? 🙏
  - name: squash and merge backport PRs after CI passes
    conditions:
      - label=backport
      - author=mergify[bot]
      - -conflict
    actions:
      queue:
        method: squash
        name: default
    
