assetbeat.inputs:
  - type: assets_aws
    regions:
        - eu-west-1
    access_key_id:
    secret_access_key:
    session_token:
    period: 600s

output.elasticsearch:
  hosts: ["localhost:9200"]
  protocol: "https"
  username: "elastic"
  password: "changeme"
  ssl.verification_mode: "none"
output.elasticsearch.allow_older_versions: true

logging.level: info
logging.to_files: false
logging.to_stderr: true
logging.selectors: ["*"]
