# Declare a Backstage Component that represents your application.
---
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: assetbeat

spec:
  type: application
  owner: group:observability-asset-management 
  lifecycle: beta 

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-assetbeat
  description: Buildkite Pipeline for assetbeat
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/assetbeat

spec:
  type: buildkite-pipeline
  owner: group:observability-asset-management
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: assetbeat
    spec:
      repository: elastic/assetbeat
      pipeline_file: ".buildkite/pipeline.yml"
      env:
        ELASTIC_PR_COMMENTS_ENABLED: 'true'
        provider_settings:
          build_pull_requests: true
          publish_commit_status: true
          publish_commit_status_per_step: true
          publish_blocked_as_pending: true
          separate_pull_request_statuses: false
          skip_pull_request_builds_for_existing_commits: false
          cancel_deleted_branch_builds: true
      teams:
        observability-asset-management:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
