agents:
  provider: "gcp"
steps:
  - label: ":wave: Greetings"            # Label (with rich emojis https://ela.st/bk-emoji).
    command: "echo 'Assetbeat pipeline'"
  - name: ":golang: mage build"
    command: "./.buildkite/scripts/build.sh"
    plugins:
      - golang#v2.0.0:
          version: 1.19.10
          import: github.com/elastic/assetbeat
  - name: ":golang: mage unitTests"
    command: "./.buildkite/scripts/tests.sh"
    plugins:
      - golang#v2.0.0:
          version: 1.19.10
          import: github.com/elastic/assetbeat