agents:
  provider: "gcp"
steps:
  - label: ":package: Package Assetbeat - Snapshot"
    if: build.branch == 'buildkite-dev'
    key: "package-snapshot"
    command: "./.buildkite/scripts/package.sh snapshot"
    artifact_paths: "build/distributions/*"
    plugins:
      - golang#v2.0.0:
          version: 1.19.10
          import: github.com/elastic/assetbeat
  - label: ":rocket: Publishing Snapshot DRA artifacts"
    if: build.branch == 'buildkite-dev'
    depends_on: "package-snapshot"
    command: "./.buildkite/scripts/publish.sh snapshot"