agents:
  provider: "gcp"
steps:
  - label: ":wave: Greetings"            # Label (with rich emojis https://ela.st/bk-emoji).
    command: "echo 'Assetbeat pipeline'"
  - name: ":golang: mage build"
    command: "./.buildkite/scripts/build.sh"
  - name: ":golang: mage unitTests"
    command: "./.buildkite/scripts/tests.sh"