agents:
  provider: "gcp"
steps:
  - label: ":package: Package Assetbeat - Snapshot"
    key: "package-snapshot"
    command: "./.buildkite/scripts/package.sh snapshot"
    artifact_paths: "build/distributions/*"
    plugins:
      - golang#v2.0.0:
          version: 1.20.5
          import: github.com/elastic/assetbeat

  - label: ":rocket: Publishing Snapshot DRA artifacts"
    if: build.branch == 'main' || build.branch =~ /^[0-9]+\.[0-9]+\$/
    depends_on: "package-snapshot"
    command: "./.buildkite/scripts/publish.sh snapshot"

  - label: ":package: Package Assetbeat - Staging"
    key: "package-staging"
    command: "./.buildkite/scripts/package.sh staging"
    artifact_paths: "build/distributions/*"
    plugins:
      - golang#v2.0.0:
          version: 1.20.5
          import: github.com/elastic/assetbeat

  - label: ":rocket: Publishing Staging DRA artifacts"
    if: build.branch =~ /^[0-9]+\.[0-9]+\$/
    depends_on: "package-staging"
    command: "./.buildkite/scripts/publish.sh staging"