---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inputrunnerconfig
  namespace: kube-system
  labels:
    k8s-app: inputrunner
data:
  inputrunner.yml: |-
      inputrunner.inputs:
         - type: assets_k8s
           period: 600s
           kube_config: ""
           asset_types: ["node", "pod", "container"]

      output.elasticsearch:
         hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
         username: ${ELASTICSEARCH_USERNAME}
         password: ${ELASTICSEARCH_PASSWORD}
         ssl.verification_mode: "none"

      logging.level: info
      logging.to_files: false
      logging.to_stderr: true
      logging.selectors: ["*"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inputrunner
  namespace: kube-system
  labels:
    k8s-app: inputrunner
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: inputrunner
  template:
    metadata:
      labels:
        k8s-app: inputrunner
    spec:
      serviceAccountName: inputrunner
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
         - name: inputrunner
           image: docker.elastic.co/observability/inputrunner:latest
           env:
                  # The basic authentication username used to connect to Elasticsearch
                  # This user needs the privileges required to publish events to Elasticsearch.
                  - name: ELASTICSEARCH_USERNAME
                    value: "elastic"
                  # The basic authentication password used to connect to Elasticsearch
                  - name: ELASTICSEARCH_PASSWORD
                    value: "changeme"
                  # The Elasticsearch host to communicate with
                  - name: ELASTICSEARCH_HOST
                    value: "elasticsearch"
                  # The Elasticsearch port to communicate with
                  - name: ELASTICSEARCH_PORT
                    value: "9200"
           volumeMounts:
                  - name: config
                    mountPath: /usr/share/inputrunner/inputrunner.yml
                    readOnly: true
                    subPath: inputrunner.yml
      volumes:
        - name: config
          configMap:
            defaultMode: 0640
            name: inputrunnerconfig
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inputrunner
  namespace: kube-system
  labels:
    k8s-app: inputrunner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inputrunner
  labels:
    k8s-app: inputrunner
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - namespaces
      - events
      - pods
      - services
      - configmaps
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources:
      - replicasets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - statefulsets
      - deployments
      - replicasets
      - daemonsets
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - ""
    resources:
      - nodes/stats
    verbs:
      - get
  - apiGroups: [ "batch" ]
    resources:
      - jobs
      - cronjobs
    verbs: [ "get", "list", "watch" ]
  # Needed for apiserver
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: inputrunner
subjects:
- kind: ServiceAccount
  name: inputrunner
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: inputrunner
  apiGroup: rbac.authorization.k8s.io
---