#!/usr/bin/env bash
set -euxo pipefail

# Install Go TODO: mode to makefile
if ! command -v go &>/dev/null; then
  echo "Go is not installed. Installing Go..."
  # shellcheck disable=SC2006
  export GO_VERSION=`cat .go-version`
  curl -O https://dl.google.com/go/go"$GO_VERSION".linux-amd64.tar.gz
  sudo tar -xf go$GO_VERSION.linux-amd64.tar.gz -C /usr/local
  # shellcheck disable=SC2016
  echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
  source ~/.bashrc
  mkdir $HOME/go
  mkdir $HOME/go/bin
  export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
  echo "Go has been installed."
else
  echo "Go is already installed."
fi

# Install mage
go install github.com/magefile/mage@latest