# Follow-on actions relating to dependabot PRs. In elastic/beats, any changes to
# dependencies contained in go.mod requires the change to be reflected in the
# NOTICE.txt file. When dependabot creates a branch for a go_modules change this
# will update the NOTICE.txt file for that change.
name: post-dependabot

on:
  push:
    branches:
      - 'dependabot/go_modules/**'

env:
  DEFAULT_GO_VERSION: "1.20"
jobs:
  update-notice:
    permissions:
      # Allow job to write to the branch.
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.DEFAULT_GO_VERSION }}
          cache: true

      - name: update notice
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: update

      - name: check for modified NOTICE.txt
        id: notice-check
        run: echo "modified=$(if git status --porcelain --untracked-files=no | grep -q -E ' NOTICE.txt$'; then echo "true"; else echo "false"; fi)" >> $GITHUB_OUTPUT

      - name: commit NOTICE.txt
        if: steps.notice-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'dependabot[bot]'
          git config --global user.email 'dependabot[bot]@users.noreply.github.com'
          git add NOTICE.txt
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -m "Update NOTICE.txt"
          git push