name: unit-test

# triggered whenever 'build' workflow completes
on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Run unit tests
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: unitTest

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: html-coverage-report
          path: coverage.html